version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: quiz
    ports:
      - "3306:3306"

  quiz-container:
    restart: always
    image: quiz
    ports:
      - "4771:4771"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql
      - angular

  angular:
    build:
      context: ./frontQuiz
      dockerfile: Dockerfile-angular
    ports:
      - "4200:4200"
    container_name: angular
    volumes:
      - ./frontQuiz:/usr/src/app/frontQuiz
      - /usr/src/app/frontQuiz/node_modules



