server:
  port: 4771

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/quiz?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
#    username: root
#    password:
  datasource:
    url: jdbc:mysql://mysql:3306/hospitalDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      jdbc:
        batch_size: 50
        fetch_size: 50
        max_size: 25
        min_size: 5
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: '[a-zA-Z0-9._]@+$Guidelines89797987forAlpabeticalArraNumeralsandOtherSybo$'


